### PR TITLE
H microverse

### PR DESCRIPTION
**Pull request by Vianney992**
Updating the HTML, CSS, readme, and .gitignore test file
HTML/CSS linter setup
Push to the remote repository
Open a pull request

### CODE REVIEW

**Review by muneebulrehman — CHANGES_REQUESTED** [review]
Hi @Vianney992 , 

Good job so far! I see you put a lot of effort into this project. However, there are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights
- No linter errors

## Required Changes ♻️
_Check the comments under the review._

- The node modules folder should not be in the remote repo. Kindly remove it. Double-check whether you are using the correct path for the node modules folder in the .gitignore file.
- test.md file should be added to the .gitignore file and should not be present in the remote repo.
- Also remove the `Live Demo` part from your readme file.
- Your commit messages are too vague and don't say anything about the things your implemented or changed. Kindly make your commit messages meaningful.

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by Vianney992** [comment]
Updating the readme file
Push to the remote repository
Open a pull request

**Review by ishimwezachee — CHANGES_REQUESTED** [review]
Hi @Vianney992 , 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.


 ## Highlights
Implimented some of the changes requested by the previous reviewer ✔️

 ## Required Changes ♻️
 

- [ ]  you've worked on the changes from the previous reviewer, but you still miss some of them. 
- I still see node_modules in your git branch, while it is not supposed to appear in remote. Please add it correctly in gitingore `node_modules/` and check if it has been deleted on remote side. 
-  As previous reviewer suggested, Add test.md file in your gitignore
-  As previous reviewer suggested, `change updated` is not a good commit message, you just have to mention what you've change, but in short words too.  [More](https://developers.google.com/blockly/guides/modify/contribute/commits)

_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by Vianney992** [comment]
Some updates : 
- remove node modules folder
- Add test.md file to the .gitignore file 
- Remove the Live Demo item from the readme file

**Review by zieeco — APPROVED** [review]
# status: APPROVED :green_circle: :100: 

Hi, @Vianney992, 


68747470733a2f2f6d656469612e67697068792e636f6d2f6d656469612f78543078657a514755357843444a754350652f67697068792e676966


Good job so far 👍 Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 


## Highlights ⚡ 

✅ Descriptive PR 👍 
✅ Linters are passing 👏 


## Optional suggestions
_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Pull request merged**
